#!/bin/bash

# Change paths to certificate and key
TARGET_DIR=/etc/nginx/ssl-certificates
CERTIFICATE_CRT=/root/.acme.sh/domain.tld/fullchain.cer
CERTIFICATE_KEY=/root/.acme.sh/domain.tld/domain.tld.key

SHASUM_CRT=($(sha256sum $CERTIFICATE_CRT))
SHASUM_KEY=($(sha256sum $CERTIFICATE_KEY))

reload_nginx=false

function copyCertificate {
  certificate=$1

  if [ -z "$certificate" ]; then
    echo "Certificate cannot be empty. Aborting"
    exit 2
  fi

  fileSum=($(sha256sum $certificate))

  if [ -f "$certificate" ]; then
    if [[ "$certificate" == *crt ]]
    then
      if [ "$fileSum" != "$SHASUM_CRT" ]
      then
        echo "Copy $CERTIFICATE_CRT to $certificate"
        rm $certificate
        cp  "$CERTIFICATE_CRT" $certificate
        reload_nginx=true
      fi
    fi
    if [[ "$certificate" == *key ]]
    then
      if [ "$fileSum" != "$SHASUM_KEY" ]
      then
        echo "Copy $CERTIFICATE_KEY to $certificate"
        rm $certificate
        cp "$CERTIFICATE_KEY" $certificate
        reload_nginx=true
      fi
    fi
  fi
}

if [ -z "$1" ]; then
  for certificate in "$TARGET_DIR"/*
  do
    copyCertificate $certificate
  done
else
  sleep 10
  copyCertificate $1
fi

if [ "$reload_nginx" = true ]
then
  echo "Reloading nginx server"
  systemctl reload nginx
fi
